[colors.bright]
black = "#6D7070"
blue = "#1BA6FA"
cyan = "#73FBF1"
green = "#B8E466"
magenta = "#A578EA"
red = "#FF4352"
white = "#FEFEF8"
yellow = "#FFD750"

[colors.normal]
black = "#0d0d0d"
blue = "#1BA6FA"
cyan = "#21DEEF"
green = "#A0E521"
magenta = "#8763B8"
red = "#FF301B"
white = "#EBEBEB"
yellow = "#FFC620"

[colors.primary]
background = "#0E1019"
foreground = "#EBEBEB"

[cursor.style]
blinking = "Never"
shape = "Underline"

[font]
size = 10

[font.bold]
family = "Fira Code"
style = "Bold"

[font.normal]
family = "Fira Code"
style = "Regular"

[window]
opacity = 0.8
